Feature ros2cli
robotpilot/ros2-seminar-examples pull request #15
Opened 2021-01-21 00:52 UTC by robotpilot

- ros2cli의 신규 command와 verbs 추가

2021-01-22 00:21 UTC, robotpilot commented
@routiful PING

2021-01-22 00:28 UTC, routiful requested changes
환경변수를 확인하고 변경까지 가능한 CLI 명령어네요. 감사합니당!
lint test 파일도 추가하셔서 `colcon test` 로 확인이 가능하겠네요. 추후 모듈별 테스트코드도 추가되면 좋을 것 같습니다. 수고하셨습니다~

2021-01-22 00:28 UTC, routiful commented on ros2env/ros2env/api/__init__.py
> +    ros_env_list = 'ROS_VERSION        = {0}\n\
문자열 시작부분부터 개행하는거 어떨까요?

2021-01-22 00:30 UTC, robotpilot commented on ros2env/ros2env/api/__init__.py
> +    ros_env_list = 'ROS_VERSION        = {0}\n\
네. 저도 그부분이 마음에 걸려서 그렇게 해봤는데... 시작부분부터 개행하면 첫줄이 비게되어 출력이 이상하게 보이더라구요.

2021-01-24 14:38 UTC, routiful approved these changes

2021-01-24 14:38 UTC, merged