Feature time example
robotpilot/ros2-seminar-examples pull request #18
Opened 2021-01-28 14:42 UTC by routiful

1. rclcpp time example의 duration 생성자 파라미터 타입 변경
2. rclpy time example 추가

2021-01-28 21:52 UTC, robotpilot requested changes
rclcpp, rclpy 까지 모두 예제가 작성되었군요. 수고했어요.
일부 수정할 부분은 코멘트 했습니다.

2021-01-28 21:52 UTC, robotpilot commented on time_rclpy_example/setup.py
> +            ['resource/' + package_name]),
윗 줄과 합치는 게 더 가독성이 좋을 듯싶어요.

2021-01-28 21:52 UTC, robotpilot commented on time_rclpy_example/time_rclpy_example/time_example/main.py
> +            duration = Duration(seconds = 1, nanoseconds = 0)
duration은 지정 후 변경이 없기에 위 rate 선언하는 부분 근처에서 선언하면 어떨까요? 매번 duration을 선언할 필요는 업슨 것 같아요. 참고로 rclcpp 예제도 마찬가지이네요.

2021-01-29 00:24 UTC, routiful commented on time_rclpy_example/setup.py
> +            ['resource/' + package_name]),
수정하였습니당

2021-01-29 00:24 UTC, routiful commented on time_rclpy_example/time_rclpy_example/time_example/main.py
> +            duration = Duration(seconds = 1, nanoseconds = 0)
넵! 그게 좋을 것 같습니다

2021-01-29 00:25 UTC, robotpilot commented
@routiful lint에도 패키지 추가해주세요.

2021-01-29 01:10 UTC, routiful commented
lint 추가하였습니다~

2021-01-29 03:17 UTC, robotpilot requested changes

2021-01-29 03:17 UTC, robotpilot commented on time_rclpy_example/setup.py
> +    entry_points={'console_scripts': ['time_example = time_rclpy_example.time_example.main:main']},
여기는 문제 없었어요. 전 11번 라인을 말씀드렸었어요.

2021-01-29 03:28 UTC, routiful commented on time_rclpy_example/setup.py
> +    entry_points={'console_scripts': ['time_example = time_rclpy_example.time_example.main:main']},
넵.재수정 하였습니다

2021-01-29 04:02 UTC, merged