Develop
robotpilot/ros2-seminar-examples pull request #8
Opened 2020-12-31 03:03 UTC by robotpilot

- `__pycache__` 폴더 삭제
- CI Travis 알림 멤버 추가
- 패키지 저자 추가
- 디스커션 https://github.com/robotpilot/ros2-seminar-examples/discussions/7 에서 언급된 service client 예제 변경

2021-01-01 05:09 UTC, routiful requested changes
제 이름이 들어가니 책임감이 생기네요 ㅎㅎ 감사합니당
client 예제에 타이머가 사라졌으니 main문의 코드도 변경하면 좋을 것 같습니당

2021-01-01 05:09 UTC, routiful commented on topic_service_action_rclpy_example/topic_service_action_rclpy_example/arithmetic/operator.py
>          self.client_futures = []
future 값 리턴을 위한 리스트는 이제 필요 없습니당

2021-01-01 05:09 UTC, routiful commented on topic_service_action_rclpy_example/topic_service_action_rclpy_example/arithmetic/operator.py
>      try:
이 아랫부분도 복사 된 future를 확인하는게 아니라 send_request로 리턴된 future 값을 기다리는게 더 간략할것 같습니당
[예시 링크](https://github.com/ros2/examples/blob/355adf068fccd1b147acd89de62ad7d1bece9a78/rclpy/services/minimal_client/examples_rclpy_minimal_client/client_async.py#L34)

2021-01-03 22:31 UTC, robotpilot commented
@routiful 제가 원하던 예제 느낌이 점점 사라지는 것 같아요.
제가 원했던 바는 ROS 튜토리얼에 나온 심플한 버전을 지향하는게 아니라 실제 사용할 수 있는 코드를 예제로 만들고 싶었어요.
ROS 튜토리얼에 나오는 예제들이 한결같이 한번의 실행으로 끝나는데 service client 라는 것은 필요시 몇번이고 재요청이 필요한 것이예요. 한번의 노드 생명 주기에서 실행하고 끝나는 것이 아니고요.

2021-01-04 00:13 UTC, robotpilot commented
@routiful 신규로 코드 수정했어요. 처음 1번은 서비스 요청이 있고, 그 후에는 유저가 원하는 시점에서 트리거를 주었을 때 서비스 콜을 하는 방식입니다.

2021-01-04 05:25 UTC, routiful commented
@robotpilot 오! 트리거를 사용하는 예제가 더 좋아 보입니다. cpp 예제도 수정하도록 하겠습니당!

2021-01-04 05:25 UTC, routiful approved these changes

2021-01-04 05:26 UTC, merged